## The Basics

In [2]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.size

15

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize

4

In [7]:
type(a)

numpy.ndarray

In [8]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [9]:
type(b)

numpy.ndarray

## Array Creation

Create an array from a regular Python list or tuple using the **array** function

In [10]:
a = np.array([2, 3, 4])
a

array([2, 3, 4])

In [11]:
a.dtype

dtype('int32')

In [12]:
a.shape

(3,)

In [13]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [14]:
b.dtype

dtype('float64')

**array** transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [15]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
b.shape

(2, 3)

The type of the array can also be explicitly specified at creation time:

In [17]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

Function **zeros** creates an array full of zeros, function **ones** creates an array full of ones

In [18]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
np.ones((2, 3, 4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

Function **empty** creates an array whose initial content is random

In [20]:
np.empty((2, 3))

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

**arange** create a sequence of numbers which is analogous to the Python built-in range, but returns an array

In [21]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

**linspace** receives as an argument the number of elements that we want, instead of step

In [22]:
from numpy import pi
np.linspace(0, 2, 9)      # 9 numbers from 0 to 2

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [23]:
x = np.linspace(0, 2 * pi, 100)
print(x)

[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.39465405 5.45812057 5.52158709 5.58505361 5.648520

In [24]:
f = np.sin(x)
print(f)

[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.13677392e-01 -5.67059864e-01
 -6.18158986e-01 -6.66769

## Printing Arrays

In [25]:
a = np.arange(6)                   # 1d array
print(a)

[0 1 2 3 4 5]


In [26]:
b = np.arange(12).reshape(4, 3)    # 2d array
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [27]:
c = np.arange(24).reshape(2, 3, 4) # 3d array
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [28]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


In [29]:
print(np.arange(10000).reshape(100, 100))

[[   0    1    2 ...   97   98   99]
 [ 100  101  102 ...  197  198  199]
 [ 200  201  202 ...  297  298  299]
 ...
 [9700 9701 9702 ... 9797 9798 9799]
 [9800 9801 9802 ... 9897 9898 9899]
 [9900 9901 9902 ... 9997 9998 9999]]


## Basic Operations 

Arithmetic operators apply **elementwise**

In [32]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [34]:
c = a - b
c

array([20, 29, 38, 47])

In [35]:
b**2

array([0, 1, 4, 9])

In [36]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [37]:
a < 35

array([ True,  True, False, False])

Product operator <font color='red'>*</font> operates elementwise. Matrix product can be performed using the <font color='red'>@</font> operator or the <font color='red'>dot</font> function method.

In [38]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
A * B     # elementwise product

array([[2, 0],
       [0, 4]])

In [39]:
A @ B     # matrix product

array([[5, 4],
       [3, 4]])

In [40]:
A.dot(B)  # matrix product

array([[5, 4],
       [3, 4]])

Some operations, such as <font color='red'>+=</font> and <font color='red'>*=</font>, act in place to modify an existing array.

In [44]:
rg = np.random.default_rng(1) # create instance of default random

In [45]:
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [46]:
b += a
b

array([[3.51182162, 3.9504637 , 3.14415961],
       [3.94864945, 3.31183145, 3.42332645]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting).

In [47]:
a = np.ones(3, dtype=np.int32)

In [48]:
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [49]:
c = a + b
c

array([1.        , 2.57079633, 4.14159265])

In [50]:
c.dtype.name

'float64'

In [51]:
d = np.exp(c * 1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [52]:
d.dtype.name

'complex128'

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the <font color='red'>ndarray</font> class.

In [53]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [54]:
a.sum()

3.1057109529998157

In [55]:
a.min()

0.027559113243068367

In [56]:
a.max()

0.8277025938204418

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the <font color='red'>axis</font> parameter you can apply an operation along the specified axis of an array:

In [57]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [64]:
b.sum(axis=0)    # sum of each column

array([12, 15, 18, 21])

In [61]:
b.min(axis=1)    # min of each row

array([0, 4, 8])

In [69]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal Functions 

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions” (<font color='red'>ufunc</font>). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [70]:
B = np.arange(3)
B

array([0, 1, 2])

In [71]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [72]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [73]:
C = np.array([2., -1., 4.])

In [74]:
np.add(B, C)

array([2., 0., 6.])

## Indexing, Slicing and Iterating

**One-dimensional** arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.

In [86]:
a = np.arange(10)**3

In [87]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [83]:
a[2]

8

In [84]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [85]:
# equivalent to a[0:6:2] = 1000;
# from start to position 6, exclusive, set every 2nd element to 1000
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729],
      dtype=int32)

In [81]:
a[::-1] # reversed a

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000],
      dtype=int32)

In [89]:
for i in a:
    print(i**(1 / 3.))

0.0
1.0
2.0
3.0
3.9999999999999996
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


**Multidimensional** arrays can have one index per axis. These indices are given in a tuple separated by commas:

In [90]:
def f(x, y):
    return 10 * x + y

In [91]:
b = np.fromfunction(f, (5, 4), dtype=int)

In [92]:
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [93]:
b[2, 3]

23

In [94]:
b[0:5, 1] # each row in the second column of b

array([ 1, 11, 21, 31, 41])

In [95]:
b[:, 1]   # equivalent to previous example

array([ 1, 11, 21, 31, 41])

In [96]:
b[1:3, :] # each column in the second and third row of b

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [97]:
b[-1]

array([40, 41, 42, 43])

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i, ...].

In [98]:
c = np.array([[[0, 1, 2],
               [10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])

In [99]:
c.shape

(2, 2, 3)

In [100]:
c[1, ...] # same as c[1, :, :] or c[1]

array([[100, 101, 102],
       [110, 112, 113]])

In [101]:
c[..., 2] # same as c[:, :, 2]

array([[  2,  13],
       [102, 113]])

**Iterating** over multidimensional arrays is done with respect to the first axis: